/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Z2tHa6SFdzI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardContent,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Room } from "@prisma/client";
import Link from "next/link";

export function RoomCard({ room }: { room: Room }) {
  return (
    <Card className="w-full max-w-sm">
      <img
        src={room.Thumbnail ?? "/404.jpg"}
        alt="Thumbnail"
        width="600"
        height="300"
        className="w-full aspect-[2/1] object-cover rounded-t-lg"
      />
      <CardContent className="p-4 flex flex-col justify-between">
        <div>
          <CardTitle className="text-xl font-semibold">{room.name}</CardTitle>
          <CardDescription className="text-muted-foreground line-clamp-1">
            {room.description}
          </CardDescription>
        </div>
        <Link href={`/browse-rooms/${room.id}`}>
          <Button className="mt-4">Join Room</Button>
        </Link>
      </CardContent>
    </Card>
  );
}
